### PR TITLE
luci-app-advanced-reboot: (Change xiaomi-ax9000.json)

### PR DESCRIPTION
**Pull request by tiagofreire-pt**
This router needs a second bootEnv variable to force the last succeeded rootfs partition.

### CODE REVIEW

**Comment by stangri** [comment]
Let me know when it's ready to merge.

**Comment by tiagofreire-pt** [comment]
It's ready to review, @stangri .

**Comment by stangri** [comment]
Great work, thank you very much!

**Comment by stangri** [comment]
The binary is available at https://github.com/stangri/repo.openwrt.melmac.net/blob/master/luci-app-advanced-reboot_1.0.1-5_all.ipk

**Pull request merged**
